{
    "custom-styles": {
    },
    "editor-colors": {
        "BackgroundColor": "#232629",
        "BracketMatching": "#8e44ad",
        "CodeFolding": "#224e65",
        "CurrentLine": "#2a2e32",
        "CurrentLineNumber": "#a5a6a8",
        "IconBorder": "#31363b",
        "IndentationLine": "#3a3f44",
        "LineNumbers": "#7a7c7d",
        "MarkBookmark": "#0404bf",
        "MarkBreakpointActive": "#8b0607",
        "MarkBreakpointDisabled": "#820683",
        "MarkBreakpointReached": "#6d6e07",
        "MarkError": "#da4453",
        "MarkExecution": "#4d4e50",
        "MarkWarning": "#f67400",
        "ModifiedLines": "#c04900",
        "ReplaceHighlight": "#808021",
        "SavedLines": "#1c8042",
        "SearchHighlight": "#218058",
        "Separator": "#3f4347",
        "SpellChecking": "#c0392b",
        "TabMarker": "#4d4d4d",
        "TemplateBackground": "#31363b",
        "TemplateFocusedPlaceholder": "#123723",
        "TemplatePlaceholder": "#123723",
        "TemplateReadOnlyPlaceholder": "#4d1f24",
        "TextSelection": "#2d5c76",
        "WordWrapMarker": "#3a3f44"
    },
    "metadata": {
        "name": "Breeze Dark test",
        "revision": 1
    },
    "text-styles": {
        "Alert": {
            "background-color": "#4d1f24",
            "bold": true,
            "selected-text-color": "#95da4c",
            "text-color": "#95da4c"
        },
        "Annotation": {
            "selected-text-color": "#27ae60",
            "text-color": "#27ae60"
        },
        "Attribute": {
            "selected-text-color": "#fdbc4b",
            "text-color": "#fdbc4b"
        },
        "BaseN": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "BuiltIn": {
            "selected-text-color": "#bdc3c7",
            "text-color": "#7f8c8d"
        },
        "Char": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#d87537"
        },
        "Comment": {
            "selected-text-color": "#418257",
            "text-color": "#418257"
        },
        "CommentVar": {
            "selected-text-color": "#94a3a4",
            "text-color": "#7f8c8d"
        },
        "Constant": {
            "bold": true,
            "selected-text-color": "#27aeae",
            "text-color": "#27aeae"
        },
        "ControlFlow": {
            "bold": true,
            "selected-text-color": "#fdbc4b",
            "text-color": "#fdbc4b"
        },
        "DataType": {
            "bold": true,
            "selected-text-color": "#fdbc4b",
            "text-color": "#2980b9"
        },
        "DecVal": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Documentation": {
            "selected-text-color": "#da4453",
            "text-color": "#a43340"
        },
        "Error": {
            "selected-text-color": "#da4453",
            "text-color": "#da4453",
            "underline": true
        },
        "Extension": {
            "bold": true,
            "selected-text-color": "#bdc3c7",
            "text-color": "#bdc3c7"
        },
        "Float": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Function": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#2980b9"
        },
        "Import": {
            "selected-text-color": "#27ae60",
            "text-color": "#27ae60"
        },
        "Information": {
            "selected-text-color": "#e46700",
            "text-color": "#c45b00"
        },
        "Keyword": {
            "bold": true,
            "selected-text-color": "#cfcfc2",
            "text-color": "#fdbc4b"
        },
        "Normal": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Operator": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Others": {
            "selected-text-color": "#27ae60",
            "text-color": "#27ae60"
        },
        "Preprocessor": {
            "selected-text-color": "#d87537",
            "text-color": "#d87537"
        },
        "RegionMarker": {
            "background-color": "#153042",
            "selected-text-color": "#3daee9",
            "text-color": "#2980b9"
        },
        "SpecialChar": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "SpecialString": {
            "selected-text-color": "#da4453",
            "text-color": "#da4453"
        },
        "String": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Variable": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "VerbatimString": {
            "selected-text-color": "#da4453",
            "text-color": "#da4453"
        },
        "Warning": {
            "selected-text-color": "#da4453",
            "text-color": "#da4453"
        }
    }
}
